### ISSUE TITLE
Can't get nextcloud to work using Director.

### ISSUE THREAD

**Issue by tschettervictor** [AppJail-makejails/nextcloud#2]
Below is the appjail-director.yml file I'm using. Everything deploys nicely and start up, but visiting the URL just gives me an empty response. It appears to be working, because if I remove my IP from the "trusted_domain" field, the nextcloud page comes up showing that error.

```
options:
  - bridge: 'iface:vtnet0 test'
  - macaddr: 'sb_test:static'
  - ifconfig: 'sb_test:inet 192.168.1.158/23'
  - defaultrouter: '192.168.0.253'

services:
  nextcloud:
    name: nextcloud
    makejail: gh+AppJail-makejails/nextcloud
    environment:
      - SQLITE_DATABASE: nextcloud
      - NEXTCLOUD_ADMIN_USER: 'nextcloud'
      - NEXTCLOUD_ADMIN_PASSWORD: 'nextcloud'
      - NEXTCLOUD_TRUSTED_DOMAINS: '192.168.1.158'
    options:
      - template: '/root/nextcloud-project/template.conf'
    arguments:
      - nextcloud_tag: '14.1-php82-apache'
    volumes:
      - apps: nextcloud-apps
      - config: nextcloud-config
      - data: nextcloud-data
      - done: nextcloud-done
      - log: nextcloud-log
      - themes: nextcloud-themes

default_volume_type: '<volumefs>'

volumes:
  apps:
    device: .volumes/apps
  config:
    device: .volumes/config
  data:
    device: .volumes/data
  done:
    device: .volumes/done
  log:
    device: .volumes/log
  themes:
    device: .volumes/themes
```
template.conf 
```
exec.start: "/bin/sh /etc/rc"
exec.stop: "/bin/sh /etc/rc.shutdown jail"
sysvshm: new
sysvsem: new
sysvmsg: new
mount.devfs
```

**Comment by DtxdF** [comment]
I will try Nextcloud to reproduce this problem.

**Comment by DtxdF** [comment]
![2024-12-02_21:18:38_1197x566](https://github.com/user-attachments/assets/eddc8384-c733-4845-a3a1-145b9547aa16)
![2024-12-02_21:16:36_1195x574](https://github.com/user-attachments/assets/2d8a842a-6594-450e-bf0c-3e9031e20ba8)
![2024-12-02_21:14:53_1198x572](https://github.com/user-attachments/assets/80d026b8-212b-41c4-94df-71388e43aa56)

I try with the following files:

**appjail-director.yml**:

```yaml
options:
  - virtualnet: ':<random> default'
  - nat:

services:
  nextcloud:
    name: nextcloud
    makejail: gh+AppJail-makejails/nextcloud
    environment:
      - SQLITE_DATABASE: nextcloud
      - NEXTCLOUD_ADMIN_USER: !ENV '${ADMIN_USER}'
      - NEXTCLOUD_ADMIN_PASSWORD: !ENV '${ADMIN_PASS}'
      - NEXTCLOUD_TRUSTED_DOMAINS: !ENV '${TRUSTED_DOMAINS}'
    options:
      - expose: !ENV '${PORT}:80 ext_if:${IFACE0} on_if:${IFACE0}'
      - template: !ENV '${PWD}/template.conf'
    volumes:
      - apps: nextcloud-apps
      - config: nextcloud-config
      - data: nextcloud-data
      - done: nextcloud-done
      - log: nextcloud-log
      - themes: nextcloud-themes
    arguments:
      - nextcloud_tag: !ENV '${TAG}'

default_volume_type: '<volumefs>'

volumes:
  apps:
    device: .volumes/apps
  config:
    device: .volumes/config
  data:
    device: .volumes/data
  done:
    device: .volumes/done
  log:
    device: .volumes/log
  themes:
    device: .volumes/themes
```

**.env**:

```
DIRECTOR_PROJECT=nextcloud
ADMIN_USER=nextcloud
ADMIN_PASS=nextcloud
TRUSTED_DOMAINS=100.79.254.10
PORT=8080
TAG=14.1-php82-apache
IFACE0=tailscale0
```

**template.conf**:

```
exec.start: "/bin/sh /etc/rc"
exec.stop: "/bin/sh /etc/rc.shutdown jail"
sysvshm: new
sysvsem: new
sysvmsg: new
mount.devfs
```

Note that I have to put some things that you don't need as the tailscale interface, because I'm on my tailnet, but it's easy to understand all the files anyway.

Maybe there is something on your system that is affecting the connection, such as a firewall. See if there is anything interesting in `/var/log/nextcloud`.

**Comment by tschettervictor** [comment]
The log is empty for nextcloud.

**Comment by DtxdF** [comment]
Do you have any other jails using the same IP as your Nextcloud jail?

I have no information from your system, so I can only make assumptions.

**Comment by tschettervictor** [comment]
Good question. I’ll get back to you on that one…

**Comment by tschettervictor** [comment]
Nope. All looks in order there.

Maybe you could try doing a VNET as I did.

**Comment by DtxdF** [comment]
What is the output of the following command?

```sh
curl -Li http://192.168.1.158/
```

You can also try to change the IP address to any other IP address and the exposed port to another one. See my example, I use 8080 as the exposed port, but Apache is listening on 80.

**Comment by DtxdF** [comment]
> You can also try to change the IP address to any other IP address and the exposed port to another one. See my example, I use 8080 as the exposed port, but Apache is listening on 80.

Sorry, I forget that you don't use Virtual Networks, but you can at least try to use any other IP address.

I will use the same network options as you to see if I can reproduce this problem.

**Comment by tschettervictor** [comment]
> > You can also try to change the IP address to any other IP address and the exposed port to another one. See my example, I use 8080 as the exposed port, but Apache is listening on 80.
> 
> Sorry, I forget that you don't use Virtual Networks, but you can at least try to use any other IP address.
> 
> I will use the same network options as you to see if I can reproduce this problem.

The curl command just hangs.
I tried another IP as well as another port. 
No go.

**Comment by DtxdF** [comment]
I have successfully reproduce this issue.

I'm not 100% sure but I think the problem is the MAC address generated based on the jail name. If you look up the MAC address on a [random website](https://www.macvendorlookup.com/) that perform this task, you will see that the MAC address is unknown, so the router is likely not allowing it to communicate with other devices that match this case.

But if you change the MAC address to a MAC address with a registered provider, the jail will be able to communicate without problems.

Try with this MAC address and you will see that the jail can communicate successfully:

```yaml
options:
  - bridge: 'iface:jext nc'
  - ifconfig: 'sb_nc:inet 192.168.1.151/24'
  - macaddr: 'sb_nc:00:1c:25:aa:bb:cb'
  - defaultrouter: '192.168.1.1'
```

I have used the following MAC address in some of my jails:

https://github.com/DtxdF/jellyfin-makejail/blob/main/Makejail#L2

**Comment by tschettervictor** [comment]
Hmmm. Some progress, but still can't get to the site.

```
curl -Li http://192.168.1.158
HTTP/1.1 302 Found
Date: Mon, 02 Dec 2024 21:55:18 GMT
Server: Apache/2.4.62 (FreeBSD) PHP/8.2.23
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: noindex, nofollow
X-XSS-Protection: 1; mode=block
X-Powered-By: PHP/8.2.23
Set-Cookie: ocpji4ukphsg=8196ufk8cjam1t4ls6hvhik9v4; path=/; HttpOnly; SameSite=Lax
Set-Cookie: oc_sessionPassphrase=h3YvMkBvqMh5Gu96%2FLcZG50csFWkGjFdrGzZYBSscTRi%2B%2BKkG1FG9GSlLU3sX%2B9rDg5A4oVgYT2h2%2BAbDccgTouhuZnLQgSW%2FhXvX07EuRmxoM1EvVgejDJuLkiEN%2BZR; path=/; HttpOnly; SameSite=Lax
Set-Cookie: ocpji4ukphsg=8196ufk8cjam1t4ls6hvhik9v4; path=/; HttpOnly; SameSite=Lax
Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-nLbPASawnM99mr5JpnXRp2us+w1nNv/Aq7yGnf1nDjs='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
Set-Cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Set-Cookie: ocpji4ukphsg=8196ufk8cjam1t4ls6hvhik9v4; path=/; HttpOnly; SameSite=Lax
Location: http://192.168.1.158/index.php/login
Content-Length: 0
Content-Type: text/html; charset=UTF-8

curl: (52) Empty reply from server
```

**Comment by tschettervictor** [comment]
Appjail is running on a VM here. 
Visiting the page shows ERR_EMPTY_RESPONSE

**Comment by tschettervictor** [comment]
Perhaps it is pulling the apache makejail for 13.4 instead of 14.1
How would I change that tag.

**Comment by DtxdF** [comment]
The latest problem seems to be Nextcloud or the nextcloud package, but I wonder why it worked without any problems when I tried the first attempt. I will look into this.

But, you can confirm what I said:

```sh
appjail-director down -d
rm -rf .volumes
appjail-director up
appjail cmd jexec nextcloud curl -Li http://localhost # empty response
appjail pkg jail nextcloud update
appjail pkg jail nextcloud upgrade
appjail service jail nextcloud apache24 restart
appjail cmd jexec nextcloud occ upgrade
appjail cmd jexec nextcloud occ maintenance:update:htaccess
```

After doing this, I can see the login site.

I have also tried with the image for 13.4 and the same problem is reproduced. The solution is the same.

I will update the images to fix this problem.

> How would I change that tag.

Using the `nextcloud_tag` argument. This is the convention for all Makejails: `<makejail-name>_tag`.

**Comment by tschettervictor** [comment]
Getting
`Error updating .htaccess file, not enough permissions, not enough free space or "overwrite.cli.url" set to an invalid URL?`

I tried changing that overwrite cli value to the IP but that didnt work. Removing that value didnt work either.

**Comment by DtxdF** [comment]
That is quite rare. If you still have your Nextcloud jail please share the output of `ls -Al /usr/local/www/apache24/data/.htaccess*`.

Anyway, I have updated and tested the image and it works as expected. These are my network options:

```yaml
options:
  - bridge: 'iface:jext nc'
  - ifconfig: 'sb_nc:inet 192.168.1.151/24'
  - macaddr: 'sb_nc:static:58:9c:fc'
  - defaultrouter: '192.168.1.1'
  - resolv_conf: !ENV '${PWD}/files/resolv.conf'
```

I also added a custom `resolv.conf(5)` because my `/etc/resolv.conf` has a nameserver that doesn't work with the jail.
